"""empty message

Revision ID: b3ec6e11cd65
Revises: 2de4db878cec
Create Date: 2021-06-21 21:22:52.469528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ec6e11cd65'
down_revision = '2de4db878cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_profile', sa.String(length=64), nullable=True),
    sa.Column('email_profile', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_email_profile'), 'profile', ['email_profile'], unique=True)
    op.create_index(op.f('ix_profile_timestamp'), 'profile', ['timestamp'], unique=False)
    op.create_index(op.f('ix_profile_username_profile'), 'profile', ['username_profile'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_username_profile'), table_name='profile')
    op.drop_index(op.f('ix_profile_timestamp'), table_name='profile')
    op.drop_index(op.f('ix_profile_email_profile'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
